#!/bin/bash
###############################################################################
# This is the main entry point to install features and programs.
#
# This script must be run as root.
#
# usage examples:
# 
# install python-base-environment
#
###############################################################################

set -e

source lib/common.sh

export USERNAME="$(default_user)"
export DEFAULT_PYTHON_VERSION=${DEFAULT_PYTHON_VERSION:-"3.11.3"}

./features/python-base-environment.sh